version: '3'
services:
    movies:
        build: .
        command: python service.py
        ports:
            - "5000:5000"
        volumes:
        - .:/service
        container_name: danno_vu_service
        networks:
            - ws_bridge
    books:
        build: ./dema4638
        ports:
            - "80:80"
        volumes:
        - .:/service
        container_name: external
        networks:
            - ws_bridge
networks:
    ws_bridge: